### Create new Todo 
POST http://localhost:8000/todos/ HTTP/1.1
Content-Type: application/json

{
  "title": "Kerja",
  "description": "Kerja cari duit!",
  "is_done": false
}

### Get a Todo by TodoID
GET http://localhost:8000/todos/1 HTTP/1.1
Content-Type: application/json

### Get all Todos
GET http://localhost:8000/todos/ HTTP/1.1
Content-Type: application/json

### Update a Todo 
PUT http://localhost:8000/todos/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Kerja",
  "description": "Kerja dapat duit!",
  "is_done": true
}

### Delete a Todo by TodoID
DELETE http://localhost:8000/todos/1 HTTP/1.1
